FROM node:22.18.0-bookworm-slim AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

ENV NODE_ENV=production
RUN npm run build

# Stage 2: minimal runtime image
FROM node:22.18.0-bookworm-slim

WORKDIR /app

# Only copy what's needed to run
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

ENV NODE_ENV=production
EXPOSE 3000


CMD ["node", "server.js"]