apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      hostAliases:
        - ip: "10.103.239.197"
          hostnames:
            - "sima.dev"
      containers:
        - name: client
          image: rosengray/sima-client
          env: 
            - name: NEXT_PUBLIC_API_URL
              value: "http://sima.dev"
            - name: MONGO_URI
              value: "mongodb://sima-mongo-srv:27017/sima"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY 
            - name: BACKBLAZEB_PUBLIC_BUCKET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backblazeb-public-bucket-access-key
                  key: BACKBLAZEB_PUBLIC_BUCKET_ACCESS_KEY
            - name: BACKBLAZEB_PUBLIC_BUCKET_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backblazeb-public-bucket-secret-key
                  key: BACKBLAZEB_PUBLIC_BUCKET_SECRET_KEY              
            - name: RECAPTCHA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: recaptcha-secret-key
                  key: RECAPTCHA_SECRET_KEY
            # Required for Server Actions to work after pod restarts (see prod client-depl comment).
            - name: NEXT_SERVER_ACTIONS_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: server-actions-encryption-key
                  key: NEXT_SERVER_ACTIONS_ENCRYPTION_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
