apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sima-mongo-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-sima
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/sima"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sima-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sima-mongo
  template:
    metadata:
      labels:
        app: sima-mongo
    spec:
      containers:
        - name: sima-mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: sima-mongo-claim
---
apiVersion: v1
kind: Service
metadata:
  name: sima-mongo-srv
spec:
  type: NodePort
  selector:
    app: sima-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30016
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate
