import type { Animal, AnimalId } from "@/lib/pets/animals/types/animal.schema";

/**
 * Animals data for the pets for-sale flow.
 * Edit this file to change animal/kind options only for for-sale;
 * for-free and accessories use their own data.
 */
export const animals: Record<AnimalId, Animal> = {
  anim_dogs: {
    id: "anim_dogs",
    russianName: "Собаки",
    kinds: [
      { id: "DgA1x9", name: "מעורב", russianName: "Метис" },
      { id: "DgB2kQ", name: "אירדייל טרייר", russianName: "Эрдельтерьер" },
      {
        id: "DgC3M8",
        name: "אלסקן מלאמוט",
        russianName: "Аляскинский маламут",
      },
      { id: "DgD4R2", name: "אפנפינצ'ר", russianName: "Аффенпинчер" },
      { id: "DgE5T7", name: "אקיטה אינו", russianName: "Акита-ину" },
      {
        id: "DgF6W4",
        name: "אקיטה אמריקאי",
        russianName: "Американская акита",
      },
      { id: "DgG7L9", name: "באסט", russianName: "Бассет-хаунд" },
      { id: "DgH8P3", name: "בוביה דה פלאנדר", russianName: "Бувье-де-Фландр" },
      {
        id: "DgJ9A6",
        name: "בול טרייר ננסי",
        russianName: "Миниатюрный бультерьер",
      },
      { id: "DgK0S8", name: "בול מאסטיף", russianName: "Бульмастиф" },
      {
        id: "DgL1D5",
        name: "בולדוג אמריקאי",
        russianName: "Американский бульдог",
      },
      { id: "DgM2F7", name: "בולדוג אנגלי", russianName: "Английский бульдог" },
      {
        id: "DgN3H4",
        name: "בולדוג צרפתי",
        russianName: "Французский бульдог",
      },
      { id: "DgP4J9", name: "בוסטון טרייר", russianName: "Бостон-терьер" },
      { id: "DgQ5K6", name: "בוסרון", russianName: "Босерон" },
      { id: "DgR6M2", name: "בוקסר", russianName: "Боксер" },
      { id: "DgS7N8", name: "בורדר קולי", russianName: "Бордер-колли" },
      { id: "DgT8Q1", name: "בורזוי", russianName: "Борзая" },
      { id: "DgU9R5", name: "ביגל", russianName: "Бигль" },
      { id: "DgV0S4", name: "בירדד קולי", russianName: "Бородатый колли" },
      { id: "DgW1T7", name: "בישון פריזה", russianName: "Бишон фризе" },
      { id: "DgX2U9", name: "בישון בולונז", russianName: "Болоньез" },
      { id: "DgY3V6", name: "בישון הוואנז", russianName: "Гаванский бишон" },
      { id: "DgZ4W8", name: "בלדההאונד", russianName: "Бладхаунд" },
      {
        id: "DgA5X2",
        name: "בקר אוסטרלי",
        russianName: "Австралийская пастушья собака",
      },
      { id: "DgB6Y4", name: "בריארד", russianName: "Бриар" },
      { id: "DgC7Z9", name: "ברניז", russianName: "Бернский зенненхунд" },
      {
        id: "DgD8A3",
        name: "ג'ק ראסל טרייר",
        russianName: "Джек-рассел-терьер",
      },
      {
        id: "DgE9B6",
        name: "גולדן רטריבר",
        russianName: "Золотистый ретривер",
      },
      { id: "DgF0C8", name: "גורדון סטר", russianName: "Сеттер гордон" },
      { id: "DgG1D2", name: "גרייהאונד", russianName: "Грейхаунд" },
      {
        id: "DgH2E7",
        name: "גריפון בריסלי",
        russianName: "Брюссельский грифон",
      },
      { id: "DgJ3F9", name: "דוברמן", russianName: "Доберман" },
      { id: "DgK4G5", name: "דוג דה בורדו", russianName: "Бордоский дог" },
      { id: "DgL5H1", name: "דוגו קאנריו", russianName: "Дого канарио" },
      { id: "DgM6J4", name: "דלמטי", russianName: "Далматин" },
      { id: "DgN7K9", name: "דני ענק", russianName: "Немецкий дог" },
      { id: "DgP8L3", name: "האסקי סיבירי", russianName: "Сибирский хаски" },
      {
        id: "DgQ9M6",
        name: "הרים פירנאי",
        russianName: "Пиренейская горная собака",
      },
      {
        id: "DgR0N8",
        name: "הרים שוויצרי",
        russianName: "Большой швейцарский зенненхунд",
      },
      { id: "DgS1P5", name: "וויפט", russianName: "Уиппет" },
      { id: "DgT2Q7", name: "וולש קורגי", russianName: "Вельш-корги" },
      { id: "DgU3R9", name: "וימרנר", russianName: "Веймаранер" },
      { id: "DgV4S2", name: "ויסלה", russianName: "Венгерская выжла" },
      {
        id: "DgW5T6",
        name: "טוי טרייר אנגלי",
        russianName: "Английский той-терьер",
      },
      {
        id: "DgX6U8",
        name: "טוי טרייר רוסי",
        russianName: "Русский той-терьер",
      },
      { id: "DgY7V1", name: "טוי רוסי", russianName: "Русский той" },
      { id: "DgZ8W4", name: "טרייר", russianName: "Терьер" },
      {
        id: "DgA9X7",
        name: "טרייר אמריקאי קירח",
        russianName: "Американский голый терьер",
      },
      {
        id: "DgB0Y9",
        name: "טרייר רוסי שחור",
        russianName: "Чёрный русский терьер",
      },
      { id: "DgC1Z5", name: "יורקשייר", russianName: "Йоркширский терьер" },
      {
        id: "DgD2A8",
        name: "כלב פרואני קירח",
        russianName: "Перуанская голая собака",
      },
      { id: "DgE3B1", name: "כנעני", russianName: "Канаанская собака" },
      { id: "DgF4C6", name: "לאונברגר", russianName: "Леонбергер" },
      { id: "DgG5D9", name: "לאסה אפסו", russianName: "Лхаса апсо" },
      { id: "DgH6E2", name: "לברדור", russianName: "Лабрадор-ретривер" },
      {
        id: "DgJ7F8",
        name: "מים פורטוגזי",
        russianName: "Португальская водяная собака",
      },
      { id: "DgK8G3", name: "מלטז", russianName: "Мальтезе" },
      {
        id: "DgL9H5",
        name: "מסטינו נפוליטנו",
        russianName: "Неаполитанский мастиф",
      },
      { id: "DgM0J7", name: "מסטיף טיבטי", russianName: "Тибетский мастиф" },
      {
        id: "DgN1K4",
        name: "מרמנו",
        russianName: "Мареммано-абруццкая овчарка",
      },
      { id: "DgP2L9", name: "ניופאונדלנד", russianName: "Ньюфаундленд" },
      { id: "DgQ3M2", name: "סאלוקי", russianName: "Салюки" },
      { id: "DgR4N6", name: "סאן ברנרד", russianName: "Сенбернар" },
      { id: "DgS5P8", name: "סטר אירי", russianName: "Ирландский сеттер" },
      { id: "DgT6Q1", name: "סטר אנגלי", russianName: "Английский сеттер" },
      { id: "DgU7R4", name: "סיני מצויץ", russianName: "Китайская хохлатая" },
      { id: "DgV8S9", name: "סמוייד", russianName: "Самоед" },
      {
        id: "DgW9T3",
        name: "ספרינגר ספנייל",
        russianName: "Английский спрингер-спаниель",
      },
      { id: "DgX0U6", name: "סקוטיש טרייר", russianName: "Шотландский терьер" },
      { id: "DgY1V8", name: "פאג", russianName: "Мопс" },
      {
        id: "DgZ2W5",
        name: "פארסון ראסל טרייר",
        russianName: "Парсон-рассел-терьер",
      },
      { id: "DgA3X9", name: "פודל", russianName: "Пудель" },
      { id: "DgB4Y2", name: "פוינטר", russianName: "Пойнтер" },
      {
        id: "DgC5Z7",
        name: "פומרניין/פומרני",
        russianName: "Померанский шпиц",
      },
      { id: "DgD6A4", name: "פוקס טרייר", russianName: "Фокстерьер" },
      { id: "DgE7B9", name: "פינצ'ר", russianName: "Пинчер" },
      { id: "DgF8C1", name: "פפיון", russianName: "Папийон" },
      { id: "DgG9D6", name: "פקינז", russianName: "Пекинес" },
      { id: "DgH0E8", name: "צ'יוואווה", russianName: "Чихуахуа" },
      { id: "DgJ1F3", name: "צאו צאו", russianName: "Чау-чау" },
      { id: "DgK2G5", name: "צין יפני", russianName: "Японский хин" },
      { id: "DgL3H9", name: "קאנה קורסו", russianName: "Кане-корсо" },
      { id: "DgM4J2", name: "קארן טרייר", russianName: "Керн-терьер" },
      {
        id: "DgN5K7",
        name: "קבליר קינג צ'ארלס",
        russianName: "Кавалер-кинг-чарльз-спаниель",
      },
      { id: "DgP6L1", name: "קוטון דה טולייר", russianName: "Котон-де-тулеар" },
      { id: "DgQ7M4", name: "קולי", russianName: "Колли" },
      { id: "DgR8N9", name: "קוקר ספניאל", russianName: "Кокер-спаниель" },
      { id: "DgS9P2", name: "קיסהאונד", russianName: "Кеесхонд" },
      { id: "DgT0Q6", name: "קנגל טורקי", russianName: "Турецкий кангал" },
      { id: "DgU1R8", name: "קרי בלו טרייר", russianName: "Керри-блю-терьер" },
      {
        id: "DgV2S3",
        name: "רועה אנטולי",
        russianName: "Анатолийская овчарка",
      },
      {
        id: "DgW3T5",
        name: "רועה אסיאתי",
        russianName: "Среднеазиатская овчарка",
      },
      { id: "DgX4U9", name: "רועה בלגי", russianName: "Бельгийская овчарка" },
      { id: "DgY5V2", name: "רועה גרמני", russianName: "Немецкая овчарка" },
      { id: "DgZ6W7", name: "רועה הולנדי", russianName: "Голландская овчарка" },
      { id: "DgA7X4", name: "רועה צ'כי", russianName: "Чешская овчарка" },
      { id: "DgB8Y9", name: "רועה קווקזי", russianName: "Кавказская овчарка" },
      {
        id: "DgC9Z1",
        name: "רועה שוויצרי לבן",
        russianName: "Белая швейцарская овчарка",
      },
      {
        id: "DgD0A5",
        name: "רועים אוסטרלי",
        russianName: "Австралийская овчарка",
      },
      {
        id: "DgE1B8",
        name: "רטריבר חלק שיער",
        russianName: "Гладкошёрстный ретривер",
      },
      {
        id: "DgF2C3",
        name: "ריצבק רודזיאן",
        russianName: "Родезийский риджбек",
      },
      { id: "DgG3D6", name: "שארפיי", russianName: "Шарпей" },
      { id: "DgH4E9", name: "שי-צו", russianName: "Ши-тцу" },
      { id: "DgJ5F2", name: "שיבא אינו", russianName: "Сиба-ину" },
      { id: "DgK6G8", name: "שיקוקו", russianName: "Сикоку" },
      { id: "DgL7H1", name: "שלטי", russianName: "Шелти" },
      { id: "DgM8J5", name: "שנאוצר", russianName: "Шнауцер" },
      { id: "DgN9K7", name: "שפיץ", russianName: "Шпиц" },
      { id: "DgP0L4", name: "תאי רידג'בק", russianName: "Тайский риджбек" },
      { id: "DgQ1M9", name: "תחש/דקל", russianName: "Такса" },
      { id: "DgR2N5", name: "אחר", russianName: "Другое" },
      { id: "DgS3P7", name: "יום אימוץ", russianName: "День усыновления" },
    ],
  },
  anim_cats: {
    id: "anim_cats",
    russianName: "Кошки",
    kinds: [
      { id: "CtA1X9", name: "אביסיני", russianName: "Абиссинская кошка" },
      { id: "CtB2K7", name: "אנגורה", russianName: "Турецкая ангора" },
      {
        id: "CtC3M4",
        name: "אקזוטי קצר שיער",
        russianName: "Экзотическая короткошёрстная",
      },
      {
        id: "CtD4R8",
        name: "בובטייל קורילי",
        russianName: "Курильский бобтейл",
      },
      { id: "CtE5T1", name: "בורמזי", russianName: "Бурманская кошка" },
      { id: "CtF6W9", name: "בירמן", russianName: "Бирманская кошка" },
      { id: "CtG7L3", name: "בנגלי", russianName: "Бенгальская кошка" },
      {
        id: "CtH8P6",
        name: "בריטי",
        russianName: "Британская короткошёрстная",
      },
      { id: "CtJ9A2", name: "דבון רקס", russianName: "Девон-рекс" },
      { id: "CtK0S7", name: "הימלאיה", russianName: "Гималайская кошка" },
      { id: "CtL1D5", name: "מיין קון", russianName: "Мейн-кун" },
      { id: "CtM2F8", name: "מעורב", russianName: "Метис" },
      { id: "CtN3H4", name: "סומלי", russianName: "Сомалийская кошка" },
      { id: "CtP4J9", name: "סיאמי", russianName: "Сиамская кошка" },
      { id: "CtQ5K6", name: "ספינקס", russianName: "Сфинкс" },
      { id: "CtR6M1", name: "סקוטי", russianName: "Шотландская кошка" },
      { id: "CtS7N8", name: "פרסי", russianName: "Персидская кошка" },
      { id: "CtT8Q3", name: "רגדול", russianName: "Рэгдолл" },
      { id: "CtU9R5", name: "רוסי כחול", russianName: "Русская голубая" },
      { id: "CtV0S4", name: "אחר", russianName: "Другое" },
      { id: "CtW1T7", name: "יום אימוץ", russianName: "День усыновления" },
    ],
  },
  anim_fish: {
    id: "anim_fish",
    russianName: "Рыбы",
    kinds: [
      { id: "87", name: "אנבסיים", russianName: "Анабасовые" },
      { id: "88", name: "דגי חתול", russianName: "Сомики" },
      { id: "179", name: "דגי מים מלוחים", russianName: "Морские рыбы" },
      { id: "93", name: "דגי מים קרים", russianName: "Холодноводные рыбы" },
      { id: "94", name: "דגים טרופיים", russianName: "Тропические рыбы" },
      { id: "89", name: "חריתיים", russianName: "Хищные рыбы" },
      { id: "90", name: "משריצי חיים", russianName: "Живородящие" },
      { id: "91", name: "נאוויתים", russianName: "Лабиринтовые" },
      { id: "92", name: "ציקלידים", russianName: "Цихлиды" },
      { id: "99", name: "אחר", russianName: "Другое" },
    ],
  },
  anim_birds: {
    id: "anim_birds",
    russianName: "Птицы",
    kinds: [
      {
        id: "B7U0T9M",
        name: "אחר",
        russianName: "Другое",
      },
      { id: "BrA9X2", name: "אקלקטוס", russianName: "Эклектус" },
      { id: "BrB4K7", name: "ג'רדין", russianName: "Жарден" },
      { id: "BrC8M1", name: "דררה", russianName: "Ожереловый попугай" },
      { id: "BrD2R9", name: "יונים", russianName: "Голуби" },
      { id: "BrE6T3", name: "כנרית", russianName: "Канарейка" },
      { id: "BrF0W8", name: "לאונייטד", russianName: "Леонейтед (порода)" },
      { id: "BrG5L4", name: "לורי", russianName: "Лори" },
      { id: "BrH7P6", name: "פיונוס", russianName: "Пионус" },
      { id: "BrJ1A9", name: "פינקים", russianName: "Финки" },
      { id: "BrK3S5", name: "פסיונים", russianName: "Фазаны" },
      { id: "BrL8D2", name: "פסיפיק", russianName: "Пацифик (попугай)" },
      {
        id: "BrM9F7",
        name: "פרקיטים אוסטרלים",
        russianName: "Австралийские попугайчики",
      },
      { id: "BrN4H1", name: "קאיק", russianName: "Каик" },
      { id: "BrP6J8", name: "קאקריקים", russianName: "Какарики" },
      { id: "BrQ0K3", name: "קוקוטייל", russianName: "Корелла" },
      { id: "BrR5M9", name: "קקדו", russianName: "Какаду" },
      { id: "BrS2N4", name: "רופלס פארוט", russianName: "Руфлес-попугай" },
      { id: "BrT7Q6", name: "תוכון", russianName: "Волнистый попугай" },
    ],
  },
  anim_ferrets: {
    id: "anim_ferrets",
    russianName: "Хорьки",
    kinds: [
      {
        "id": "FmA7K2",
        "name": "חמוס",
        "russianName": "Хорёк"
      }  
    ],
  },
  anim_rodents: {
    id: "anim_rodents",
    russianName: "Грызуны",
    kinds: [
      { "id": "a9Q2Lm", "name": "אוגר", "russianName": "Хомяк" },
      { "id": "kT7pX1", "name": "אוגר אנגורה", "russianName": "Ангорский хомяк" },
      { "id": "V3n8cB", "name": "אוגר סיבירי", "russianName": "Сибирский хомяк" },
      { "id": "m6J1Qw", "name": "ארנב \\ שפן", "russianName": "Кролик / Заяц" },
      { "id": "R5u2Hd", "name": "ארנב אנגורה", "russianName": "Ангорский кролик" },
      { "id": "z1W4eK", "name": "ארנב ננסי", "russianName": "Карликовый кролик" },
      { "id": "p8L0sN", "name": "ארנב ראש אריה", "russianName": "Львиноголовый кролик" },
      { "id": "x2C9vM", "name": "ארנב שמוט אוזניים", "russianName": "Вислоухий кролик" },
      { "id": "h7G3tP", "name": "גרביל", "russianName": "Песчанка" },
      { "id": "Q4d6Yj", "name": "דגו - צ'ינצ'ילה מידברית", "russianName": "Дегу" },
      { "id": "n3F8rA", "name": "חולדה", "russianName": "Крыса" },
      { "id": "u0K5bZ", "name": "סנאי מעופף \\ שוגר", "russianName": "Сахарный поссум / Летяга" },
      { "id": "c6S2nT", "name": "עכבר", "russianName": "Мышь" },
      { "id": "t9H1xC", "name": "צ'ינצ'ילה", "russianName": "Шиншилла" },
      { "id": "B2m7qV", "name": "שרקן \\ קביה", "russianName": "Морская свинка" },
      { "id": "j5P0wR", "name": "אחר", "russianName": "Другое" }
  
    ],
  },
  anim_farm_animals: {
    id: "anim_farm_animals",
    russianName: "сельскохозяйственные животные",
    kinds: [
      { "id": "238", "name": "אורפינגטון", "russianName": "Орпингтон" },
      { "id": "239", "name": "בלאדי", "russianName": "Блэди" },
      { "id": "240", "name": "ברהמה", "russianName": "Брама" },
      { "id": "241", "name": "הודו", "russianName": "Индюк" },
      { "id": "242", "name": "לגהורן", "russianName": "Леггорн" },
      { "id": "243", "name": "מאראנס", "russianName": "Маран" },
      { "id": "244", "name": "מנדרין", "russianName": "Мандаринка" },
      { "id": "245", "name": "סאסקס", "russianName": "Сассекс" },
      { "id": "246", "name": "סרהמה", "russianName": "Серама" },
      { "id": "247", "name": "פולני", "russianName": "Польская (хохлатая)" },
      { "id": "248", "name": "פלימות רוק", "russianName": "Плимутрок" },
      { "id": "249", "name": "פקין", "russianName": "Пекинская (утка)" },
      { "id": "250", "name": "רוד איילנד", "russianName": "Род-Айленд" },
      { "id": "213", "name": "כבשים", "russianName": "Овцы" },
      { "id": "212", "name": "עזים", "russianName": "Козы" },
      { "id": "211", "name": "פרות", "russianName": "Коровы" },
      { "id": "j5P0wR", "name": "אחר", "russianName": "Другое" }
  
    ],
  },
  anim_horses: {
    id: "anim_horses",
    russianName: "Лошади",
    kinds: [
      { "id": "81", "name": "אנדלוסי", "russianName": "Андалузская" },
      { "id": "74", "name": "אפלוסה", "russianName": "Аппалуза" },
      { "id": "83", "name": "הנובר", "russianName": "Ганноверская" },
      { "id": "85", "name": "וולש", "russianName": "Уэльский пони" },
      { "id": "84", "name": "טורבדריד", "russianName": "Торобред (чистокровная верховая)" },
      { "id": "82", "name": "טנסי", "russianName": "Теннесийская прогулочная" },
      { "id": "174", "name": "מיזורי פוקס", "russianName": "Миссури фокстроттер" },
      { "id": "260", "name": "סינגל פוט", "russianName": "Синглфут" },
      { "id": "75", "name": "ערבי", "russianName": "Арабская" },
      { "id": "78", "name": "פוני", "russianName": "Пони" },
      { "id": "77", "name": "פוני שאלטן", "russianName": "Шетландский пони" },
      { "id": "79", "name": "פיינט", "russianName": "Пейнт (American Paint Horse)" },
      { "id": "80", "name": "פלמינו", "russianName": "Паломино" },
      { "id": "130", "name": "פריזן", "russianName": "Фризская" },
      { "id": "73", "name": "קווטר", "russianName": "Квотерхорс" },
      { "id": "86", "name": "אחר", "russianName": "Другое" }
  
    ],
  },
  anim_reptiles: {
    id: "anim_reptiles",
    russianName: "Ящерицы и змеи",
    kinds: [
      { "id": "102", "name": "איגואנה", "russianName": "Игуана" },
      { "id": "48", "name": "אנדורס", "russianName": "Амадины" },
      { "id": "43", "name": "אנקונדה", "russianName": "Анаконда" },
      { "id": "39", "name": "בואה", "russianName": "Удав (Буа)" },
      { "id": "44", "name": "בורמזי אלבינו", "russianName": "Бирманский питон (альбинос)" },
      { "id": "46", "name": "בירית", "russianName": "Гартеровый уж" },
      { "id": "50", "name": "ג'אנגל", "russianName": "Джангл (морфа питона)" },
      { "id": "45", "name": "דורנגו", "russianName": "Дуранго (морфа питона)" },
      { "id": "100", "name": "חרדון", "russianName": "Бородатая агама" },
      { "id": "41", "name": "כרכן תירס", "russianName": "Маисовый полоз" },
      { "id": "49", "name": "מילק סנייק", "russianName": "Молочная змея" },
      { "id": "38", "name": "פיתון", "russianName": "Питон" },
      { "id": "47", "name": "פיתון מתכדר", "russianName": "Королевский питон" },
      { "id": "40", "name": "קינג אורנג'", "russianName": "Оранжевый королевский полоз" },
      { "id": "42", "name": "קינג סנייק", "russianName": "Королевская змея" },
      { "id": "51", "name": "שממית", "russianName": "Геккон" },
      { "id": "101", "name": "אחר", "russianName": "Другое" }
  
    ],
  },
};
