FROM node:alpine

WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .

# Expose debugging port
EXPOSE 3000
EXPOSE 9229
RUN chmod +x node_modules/.bin/ts-node-dev
CMD ["npm", "run", "start:debug"]