apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: rosengray/sima-client
          env: 
            - name: NEXT_PUBLIC_API_URL
              value: "https://www.sima-board.com"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: BACKBLAZEB_PUBLIC_BUCKET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backblazeb-public-bucket-access-key
                  key: BACKBLAZEB_PUBLIC_BUCKET_ACCESS_KEY
            - name: BACKBLAZEB_PUBLIC_BUCKET_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backblazeb-public-bucket-secret-key
                  key: BACKBLAZEB_PUBLIC_BUCKET_SECRET_KEY  
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
