apiVersion: apps/v1
kind: Deployment
metadata:
  name: professionals-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: professionals
  template:
    metadata:
      labels:
        app: professionals
    spec:
      containers:
        - name: professionals
          image: rosengray/sima-professionals
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: "sima"
            - name: NODE_ENV
              value: "production"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-user-name
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: DB_PASSWORD
            - name: BACKBLAZEB_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: backblazeb-base-url
                  key: BACKBLAZEB_BASE_URL
              - name: BACKBLAZEB_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: backblazeb-endpoint
                  key: BACKBLAZEB_ENDPOINT
              - name: BACKBLAZEB_REGION
              valueFrom:
                secretKeyRef:
                  name: backblazeb-region
                  key: BACKBLAZEB_REGION
            - name: BACKBLAZEB_PUBLIC_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: backblazeb-public-bucket-name
                  key: BACKBLAZEB_PUBLIC_BUCKET_NAME
            - name: BACKBLAZEB_PUBLIC_BUCKET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backblazeb-public-bucket-access-key
                  key: BACKBLAZEB_PUBLIC_BUCKET_ACCESS_KEY
            - name: BACKBLAZEB_PUBLIC_BUCKET_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backblazeb-public-bucket-secret-key
                  key: BACKBLAZEB_PUBLIC_BUCKET_SECRET_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: professionals-srv
spec:
  selector:
    app: professionals
  ports:
    - name: professionals
      protocol: TCP
      port: 3000
      targetPort: 3000
