interface CommercialRealEstateIconProps {
  width?: number;
  height?: number;
  viewBox?: {
    width: number;
    height: number;
  };
}
const CommercialRealEstateIcon = ({
  width,
  height,
  viewBox = { width: 120, height: 120 },
}: CommercialRealEstateIconProps) => {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={width}
      height={height}
      viewBox={`0 0 ${viewBox?.width} ${viewBox?.height}`}
      fill="none"
    >
      <defs>
        <linearGradient
          id="buildingGrad"
          x1="0%"
          y1="0%"
          x2="0%"
          y2="100%"
          gradientUnits="userSpaceOnUse"
        >
          <stop offset="0" stopColor="#818cf8" />
          <stop offset="1" stopColor="#4f46e5" />
        </linearGradient>
      </defs>
      <circle cx="60" cy="60" r="58" fill="#e0e7ff" opacity="0.3" />
      <ellipse cx="60" cy="90" rx="45" ry="3" fill="#000000" opacity="0.2" />
      <rect
        x="40"
        y="25"
        width="40"
        height="65"
        rx="2"
        fill="url(#buildingGrad)"
        stroke="#4f46e5"
        strokeWidth="2"
      />
      <rect
        x="45"
        y="30"
        width="8"
        height="9"
        rx="0.5"
        fill="#fef3c7"
        stroke="#6366f1"
        strokeWidth="1"
      />
      <rect
        x="56"
        y="30"
        width="8"
        height="9"
        rx="0.5"
        fill="#fef3c7"
        stroke="#6366f1"
        strokeWidth="1"
      />
      <rect
        x="67"
        y="30"
        width="8"
        height="9"
        rx="0.5"
        fill="#fef3c7"
        stroke="#6366f1"
        strokeWidth="1"
      />
      <rect
        x="45"
        y="42"
        width="8"
        height="9"
        rx="0.5"
        fill="#fef3c7"
        stroke="#6366f1"
        strokeWidth="1"
      />
      <rect
        x="56"
        y="42"
        width="8"
        height="9"
        rx="0.5"
        fill="#fef3c7"
        stroke="#6366f1"
        strokeWidth="1"
      />
      <rect
        x="67"
        y="42"
        width="8"
        height="9"
        rx="0.5"
        fill="#fef3c7"
        stroke="#6366f1"
        strokeWidth="1"
      />
      <rect
        x="45"
        y="54"
        width="8"
        height="9"
        rx="0.5"
        fill="#fef3c7"
        stroke="#6366f1"
        strokeWidth="1"
      />
      <rect
        x="56"
        y="54"
        width="8"
        height="9"
        rx="0.5"
        fill="#fef3c7"
        stroke="#6366f1"
        strokeWidth="1"
      />
      <rect
        x="67"
        y="54"
        width="8"
        height="9"
        rx="0.5"
        fill="#fef3c7"
        stroke="#6366f1"
        strokeWidth="1"
      />
      <rect
        x="45"
        y="66"
        width="8"
        height="9"
        rx="0.5"
        fill="#fef3c7"
        stroke="#6366f1"
        strokeWidth="1"
      />
      <rect
        x="56"
        y="66"
        width="8"
        height="9"
        rx="0.5"
        fill="#fef3c7"
        stroke="#6366f1"
        strokeWidth="1"
      />
      <rect
        x="67"
        y="66"
        width="8"
        height="9"
        rx="0.5"
        fill="#fef3c7"
        stroke="#6366f1"
        strokeWidth="1"
      />
      <rect
        x="45"
        y="78"
        width="8"
        height="9"
        rx="0.5"
        fill="#fef3c7"
        stroke="#6366f1"
        strokeWidth="1"
      />
      <rect
        x="56"
        y="78"
        width="8"
        height="9"
        rx="0.5"
        fill="#fef3c7"
        stroke="#6366f1"
        strokeWidth="1"
      />
      <rect
        x="67"
        y="78"
        width="8"
        height="9"
        rx="0.5"
        fill="#fef3c7"
        stroke="#6366f1"
        strokeWidth="1"
      />
      <rect
        x="38"
        y="22"
        width="44"
        height="4"
        fill="#3730a3"
        stroke="#312e81"
        strokeWidth="1"
      />
      <rect
        x="50"
        y="80"
        width="20"
        height="10"
        rx="1"
        fill="#1e1b4b"
        stroke="#312e81"
        strokeWidth="1.5"
      />
      <path d="M60 80 L60 90" stroke="#fef3c7" strokeWidth="1.5" />
      <path d="M50 85 L70 85" stroke="#fef3c7" strokeWidth="1.5" />
      <rect
        x="20"
        y="55"
        width="20"
        height="35"
        rx="2"
        fill="#8b5cf6"
        stroke="#7c3aed"
        strokeWidth="1.5"
      />
      <rect
        x="23"
        y="60"
        width="5"
        height="6"
        rx="0.5"
        fill="#fef3c7"
        stroke="#8b5cf6"
        strokeWidth="0.8"
      />
      <rect
        x="31"
        y="60"
        width="5"
        height="6"
        rx="0.5"
        fill="#fef3c7"
        stroke="#8b5cf6"
        strokeWidth="0.8"
      />
      <rect
        x="23"
        y="70"
        width="5"
        height="6"
        rx="0.5"
        fill="#fef3c7"
        stroke="#8b5cf6"
        strokeWidth="0.8"
      />
      <rect
        x="31"
        y="70"
        width="5"
        height="6"
        rx="0.5"
        fill="#fef3c7"
        stroke="#8b5cf6"
        strokeWidth="0.8"
      />
      <rect
        x="23"
        y="80"
        width="5"
        height="6"
        rx="0.5"
        fill="#fef3c7"
        stroke="#8b5cf6"
        strokeWidth="0.8"
      />
      <rect
        x="31"
        y="80"
        width="5"
        height="6"
        rx="0.5"
        fill="#fef3c7"
        stroke="#8b5cf6"
        strokeWidth="0.8"
      />
      <rect
        x="80"
        y="60"
        width="20"
        height="30"
        rx="2"
        fill="#a78bfa"
        stroke="#8b5cf6"
        strokeWidth="1.5"
      />
      <rect
        x="83"
        y="65"
        width="5"
        height="5"
        rx="0.5"
        fill="#fef3c7"
        stroke="#a78bfa"
        strokeWidth="0.8"
      />
      <rect
        x="91"
        y="65"
        width="5"
        height="5"
        rx="0.5"
        fill="#fef3c7"
        stroke="#a78bfa"
        strokeWidth="0.8"
      />
      <rect
        x="83"
        y="74"
        width="5"
        height="5"
        rx="0.5"
        fill="#fef3c7"
        stroke="#a78bfa"
        strokeWidth="0.8"
      />
      <rect
        x="91"
        y="74"
        width="5"
        height="5"
        rx="0.5"
        fill="#fef3c7"
        stroke="#a78bfa"
        strokeWidth="0.8"
      />
      <rect
        x="83"
        y="83"
        width="5"
        height="5"
        rx="0.5"
        fill="#fef3c7"
        stroke="#a78bfa"
        strokeWidth="0.8"
      />
      <rect
        x="91"
        y="83"
        width="5"
        height="5"
        rx="0.5"
        fill="#fef3c7"
        stroke="#a78bfa"
        strokeWidth="0.8"
      />
      <rect
        x="45"
        y="10"
        width="30"
        height="10"
        rx="2"
        fill="#10b981"
        stroke="#059669"
        strokeWidth="1.5"
      />
      <rect
        x="48"
        y="13"
        width="8"
        height="2"
        rx="0.5"
        fill="#ffffff"
        opacity="0.9"
      />
      <rect
        x="57"
        y="13"
        width="12"
        height="2"
        rx="0.5"
        fill="#ffffff"
        opacity="0.9"
      />
      <rect
        x="86"
        y="25"
        width="12"
        height="9"
        rx="1"
        fill="#fbbf24"
        stroke="#f59e0b"
        strokeWidth="1.5"
      />
      <rect
        x="87"
        y="23"
        width="10"
        height="3"
        rx="0.5"
        fill="#f59e0b"
        stroke="#d97706"
        strokeWidth="1"
      />
      <path
        d="M90 23 C91 21 93 21 94 23"
        fill="none"
        stroke="#92400e"
        strokeWidth="2"
      />
    </svg>
  );
};

export default CommercialRealEstateIcon;
