import {
  Yad2Category,
  Yad2CategoryId,
} from "./types/yad2Category.schema";

export const yad2Categories: Record<Yad2CategoryId, Yad2Category> = {
  "44": {
    id: "44",
    name: "מוצרי חשמל",
    russianName: "Бытовая техника и электроника",
    subCategories: [
      { id: "טלוויזיות", name: "טלוויזיות", russianName: "Телевизоры" },
      { id: "מקררים", name: "מקררים", russianName: "Холодильники" },
      { id: "מכונות כביסה", name: "מכונות כביסה", russianName: "Стиральные машины" },
      { id: "תנורים", name: "תנורים", russianName: "Духовки" },
      { id: "מזגנים", name: "מזגנים", russianName: "Кондиционеры" },
      { id: "מכונות קפה", name: "מכונות קפה", russianName: "Кофемашины" },
      { id: "מדיחי כלים", name: "מדיחי כלים", russianName: "Посудомоечные машины" },
      { id: "מייבשי כביסה", name: "מייבשי כביסה", russianName: "Сушильные машины" },
      { id: "תנורי מיקרוגל", name: "תנורי מיקרוגל", russianName: "Микроволновые печи" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "45": {
    id: "45",
    name: "ריהוט",
    russianName: "Мебель",
    subCategories: [
      { id: "ספות", name: "ספות", russianName: "Диваны" },
      { id: "מיטות", name: "מיטות", russianName: "Кровати" },
      { id: "שולחנות", name: "שולחנות", russianName: "Столы" },
      { id: "כורסאות", name: "כורסאות", russianName: "Кресла" },
      { id: "כסאות", name: "כסאות", russianName: "Стулья" },
      { id: "מטבחים", name: "מטבחים", russianName: "Кухни" },
      { id: "שידות", name: "שידות", russianName: "Тумбы" },
      { id: "פינת אוכל", name: "פינת אוכל", russianName: "Обеденная зона" },
      { id: "סלון", name: "סלון", russianName: "Гостиная" },
      { id: "ארון בגדים", name: "ארון בגדים", russianName: "Гардероб" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "46": {
    id: "46",
    name: "תכולת דירה",
    russianName: "Содержимое квартиры",
    subCategories: [
      { id: "וילונות", name: "וילונות", russianName: "Шторы" },
      { id: "שטיחים", name: "שטיחים", russianName: "Ковры" },
      { id: "מנורות", name: "מנורות", russianName: "Светильники" },
      { id: "אביזרי נוי", name: "אביזרי נוי", russianName: "Декор" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "47": {
    id: "47",
    name: "כלי נגינה",
    russianName: "Музыкальные инструменты",
    subCategories: [
      { id: "גיטרות", name: "גיטרות", russianName: "Гитары" },
      { id: "פסנתרים", name: "פסנתרים", russianName: "Пианино" },
      { id: "תופים", name: "תופים", russianName: "Барабаны" },
      { id: "קלידים", name: "קלידים", russianName: "Синтезаторы" },
      { id: "כלי נשיפה", name: "כלי נשיפה", russianName: "Духовые инструменты" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "48": {
    id: "48",
    name: "סלולרי",
    russianName: "Мобильные телефоны",
    subCategories: [
      { id: "סמארטפונים", name: "סמארטפונים", russianName: "Смартфоны" },
      { id: "טאבלטים", name: "טאבלטים", russianName: "Планшеты" },
      { id: "אביזרים", name: "אביזרים", russianName: "Аксессуары" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "49": {
    id: "49",
    name: "מחשבים וציוד נלווה",
    russianName: "Компьютеры и периферия",
    subCategories: [
      { id: "מחשבים ניידים", name: "מחשבים ניידים", russianName: "Ноутбуки" },
      { id: "מחשבים נייחים", name: "מחשבים נייחים", russianName: "Стационарные компьютеры" },
      { id: "מסכי מחשב", name: "מסכי מחשב", russianName: "Мониторы" },
      { id: "מדפסות", name: "מדפסות", russianName: "Принтеры" },
      { id: "מקלדות ועכברים", name: "מקלדות ועכברים", russianName: "Клавиатуры и мыши" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "51": {
    id: "51",
    name: "סטריאו ונגנים",
    russianName: "Стереосистемы и плееры",
    subCategories: [
      { id: "נגני מוזיקה", name: "נגני מוזיקה", russianName: "Плееры" },
      { id: "רמקולים", name: "רמקולים", russianName: "Колонки" },
      { id: "אוזניות", name: "אוזניות", russianName: "Наушники" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "53": {
    id: "53",
    name: "יד-שניה לנשים",
    russianName: "Секонд-хенд для женщин",
    subCategories: [
      { id: "שמלות", name: "שמלות", russianName: "Платья" },
      { id: "מכנסיים", name: "מכנסיים", russianName: "Брюки" },
      { id: "מעילים", name: "מעילים", russianName: "Пальто" },
      { id: "נעליים", name: "נעליים", russianName: "Обувь" },
      { id: "תיקים", name: "תיקים", russianName: "Сумки" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "54": {
    id: "54",
    name: "לתינוק ולילד",
    russianName: "Для малышей и детей",
    subCategories: [
      { id: "עגלות וטיולונים", name: "עגלות וטיולונים", russianName: "Коляски и коляски-трости" },
      { id: "מיטות תינוק", name: "מיטות תינוק", russianName: "Детские кроватки" },
      { id: "בגדי תינוק", name: "בגדי תינוק", russianName: "Детская одежда" },
      { id: "צעצועים", name: "צעצועים", russianName: "Игрушки" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "55": {
    id: "55",
    name: "ציוד ספורט",
    russianName: "Спортивный инвентарь",
    subCategories: [
      { id: "משקולות", name: "משקולות", russianName: "Гантели" },
      { id: "מכשירי כושר", name: "מכשירי כושר", russianName: "Тренажёры" },
      { id: "ציוד ים ובריכה", name: "ציוד ים ובריכה", russianName: "Для пляжа и бассейна" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "57": {
    id: "57",
    name: "אופניים",
    russianName: "Велосипеды",
    subCategories: [
      { id: "אופני הר", name: "אופני הר", russianName: "Горные велосипеды" },
      { id: "אופני כביש", name: "אופני כביש", russianName: "Шоссейные велосипеды" },
      { id: "אופניים חשמליים", name: "אופניים חשמליים", russianName: "Электровелосипеды" },
      { id: "חלקים ואביזרים", name: "חלקים ואביזרים", russianName: "Запчасти и аксессуары" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "63": {
    id: "63",
    name: "צילום",
    russianName: "Фото и видеотехника",
    subCategories: [
      { id: "מצלמות", name: "מצלמות", russianName: "Камеры" },
      { id: "עדשות", name: "עדשות", russianName: "Объективы" },
      { id: "תאורה", name: "תאורה", russianName: "Освещение" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "64": {
    id: "64",
    name: "אבדות",
    russianName: "Потерянные вещи",
    subCategories: [],
  },
  "65": {
    id: "65",
    name: "למסירה",
    russianName: "Отдам даром",
    subCategories: [],
  },
  "66": {
    id: "66",
    name: "שונות",
    russianName: "Разное",
    subCategories: [
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "67": {
    id: "67",
    name: "אספנות",
    russianName: "Коллекционирование",
    subCategories: [
      { id: "מטבעות", name: "מטבעות", russianName: "Монеты" },
      { id: "בולים", name: "בולים", russianName: "Марки" },
      { id: "וינטג'", name: "וינטג'", russianName: "Винтаж" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "68": {
    id: "68",
    name: "ציוד משרדי",
    russianName: "Офисное оборудование",
    subCategories: [
      { id: "מחשבים", name: "מחשבים", russianName: "Компьютеры" },
      { id: "מדפסות ומכונות צילום", name: "מדפסות ומכונות צילום", russianName: "Принтеры и копиры" },
      { id: "ריהוט משרדי", name: "ריהוט משרדי", russianName: "Офисная мебель" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "152": {
    id: "152",
    name: "משחקים וקונסולות",
    russianName: "Игры и консоли",
    subCategories: [
      { id: "קונסולות משחק", name: "קונסולות משחק", russianName: "Игровые консоли" },
      { id: "משחקי וידאו", name: "משחקי וידאו", russianName: "Видеоигры" },
      { id: "משחקי קופסה", name: "משחקי קופסה", russianName: "Настольные игры" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "155": {
    id: "155",
    name: "כלי מטבח",
    russianName: "Кухонная утварь",
    subCategories: [
      { id: "כלי בישול", name: "כלי בישול", russianName: "Посуда для готовки" },
      { id: "כלי הגשה", name: "כלי הגשה", russianName: "Посуда для сервировки" },
      { id: "אביזרי מטבח", name: "אביזרי מטבח", russianName: "Кухонные аксессуары" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "167": {
    id: "167",
    name: "ציוד לדיג'יי ואולפנים",
    russianName: "Оборудование для диджеев и студий",
    subCategories: [
      { id: "מיקסרים", name: "מיקסרים", russianName: "Микшеры" },
      { id: "כרטיסי קול", name: "כרטיסי קול", russianName: "Звуковые карты" },
      { id: "מיקרופונים", name: "מיקרופונים", russianName: "Микрофоны" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "188": {
    id: "188",
    name: "צעצועי ילדים",
    russianName: "Детские игрушки",
    subCategories: [
      { id: "בובות", name: "בובות", russianName: "Куклы" },
      { id: "משחקי הרכבה", name: "משחקי הרכבה", russianName: "Конструкторы" },
      { id: "צעצועים אלקטרוניים", name: "צעצועים אלקטרוניים", russianName: "Электронные игрушки" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "228": {
    id: "228",
    name: "מיגון לבית ולעסק",
    russianName: "Защита для дома и бизнеса",
    subCategories: [
      { id: "מצלמות אבטחה", name: "מצלמות אבטחה", russianName: "Камеры наблюдения" },
      { id: "מיגון חלונות", name: "מיגון חלונות", russianName: "Защита окон" },
      { id: "מיגון אחר", name: "מיגון אחר", russianName: "Другая защита" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "229": {
    id: "229",
    name: "קורקינטים",
    russianName: "Самокаты",
    subCategories: [
      { id: "קורקינט חשמלי", name: "קורקינט חשמלי", russianName: "Электросамокаты" },
      { id: "קורקינט רגיל", name: "קורקינט רגיל", russianName: "Обычные самокаты" },
      { id: "חלקים ואביזרים", name: "חלקים ואביזרים", russianName: "Запчасти и аксессуары" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "230": {
    id: "230",
    name: "כלי עבודה",
    russianName: "Инструменты",
    subCategories: [
      { id: "כלי עבודה ידניים", name: "כלי עבודה ידניים", russianName: "Ручной инструмент" },
      { id: "כלי עבודה חשמליים", name: "כלי עבודה חשמליים", russianName: "Электроинструмент" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "298": {
    id: "298",
    name: "קמפינג ונופש",
    russianName: "Кемпинг и отдых",
    subCategories: [
      { id: "אוהלים", name: "אוהלים", russianName: "Палатки" },
      { id: "שקי שינה", name: "שקי שינה", russianName: "Спальные мешки" },
      { id: "ציוד מחנאות", name: "ציוד מחנאות", russianName: "Туристическое снаряжение" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "302": {
    id: "302",
    name: "תכשיטים",
    russianName: "Ювелирные изделия",
    subCategories: [
      { id: "טבעות", name: "טבעות", russianName: "Кольца" },
      { id: "שרשראות", name: "שרשראות", russianName: "Цепочки" },
      { id: "עגילים", name: "עגילים", russianName: "Серьги" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "303": {
    id: "303",
    name: "משקפיים",
    russianName: "Очки",
    subCategories: [
      { id: "משקפי ראייה", name: "משקפי ראייה", russianName: "Очки для зрения" },
      { id: "משקפי שמש", name: "משקפי שמש", russianName: "Солнцезащитные очки" },
      { id: "אביזרים", name: "אביזרים", russianName: "Аксессуары" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "306": {
    id: "306",
    name: "לחתן ולכלה",
    russianName: "Для молодожёнов",
    subCategories: [
      { id: "שמלות כלה", name: "שמלות כלה", russianName: "Свадебные платья" },
      { id: "אביזרי חתונה", name: "אביזרי חתונה", russianName: "Свадебные аксессуары" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "309": {
    id: "309",
    name: "חפצי נוי",
    russianName: "Декор и предметы интерьера",
    subCategories: [
      { id: "מנורות", name: "מנורות", russianName: "Светильники" },
      { id: "פסלים וחפצי נוי", name: "פסלים וחפצי נוי", russianName: "Скульптуры и декор" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "310": {
    id: "310",
    name: "יודאיקה",
    russianName: "Иудаика",
    subCategories: [
      { id: "חנוכיות", name: "חנוכיות", russianName: "Ханукии" },
      { id: "ספרי קודש", name: "ספרי קודש", russianName: "Религиозные книги" },
      { id: "אביזרי יודאיקה", name: "אביזרי יודאיקה", russianName: "Иудаика" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "311": {
    id: "311",
    name: "פורים",
    russianName: "Пурим",
    subCategories: [
      { id: "תחפושות", name: "תחפושות", russianName: "Костюмы" },
      { id: "אביזרי פורים", name: "אביזרי פורים", russianName: "Аксессуары для Пурима" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "316": {
    id: "316",
    name: "אלטרנטיבי",
    russianName: "Альтернативное",
    subCategories: [
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "317": {
    id: "317",
    name: "סוכות",
    russianName: "Суккот",
    subCategories: [
      { id: "סוכות", name: "סוכות", russianName: "Суккот" },
      { id: "אביזרי סוכות", name: "אביזרי סוכות", russianName: "Аксессуары для сукки" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "321": {
    id: "321",
    name: "סטוקים",
    russianName: "Стоковая одежда",
    subCategories: [
      { id: "ביגוד", name: "ביגוד", russianName: "Одежда" },
      { id: "נעליים", name: "נעליים", russianName: "Обувь" },
      { id: "אביזרים", name: "אביזרים", russianName: "Аксессуары" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "350": {
    id: "350",
    name: "ביגוד ואביזרים",
    russianName: "Одежда и аксессуары",
    subCategories: [
      { id: "ביגוד ואקססוריז", name: "ביגוד ואקססוריז", russianName: "Одежда и аксессуары" },
      { id: "נעליים", name: "נעליים", russianName: "Обувь" },
      { id: "תיקים", name: "תיקים", russianName: "Сумки" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "351": {
    id: "351",
    name: "כלים סניטריים",
    russianName: "Сантехника",
    subCategories: [
      { id: "כיורים", name: "כיורים", russianName: "Раковины" },
      { id: "ברזים", name: "ברזים", russianName: "Смесители" },
      { id: "אביזרי אמבטיה", name: "אביזרי אמבטיה", russianName: "Аксессуары для ванной" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "352": {
    id: "352",
    name: "לבית",
    russianName: "Для дома",
    subCategories: [
      { id: "מנורות", name: "מנורות", russianName: "Светильники" },
      { id: "וילונות", name: "וילונות", russianName: "Шторы" },
      { id: "אביזרי בית", name: "אביזרי בית", russianName: "Домашние аксессуары" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "353": {
    id: "353",
    name: "לגינה",
    russianName: "Для сада",
    subCategories: [
      { id: "כלים לגינה", name: "כלים לגינה", russianName: "Садовый инвентарь" },
      { id: "ריהוט גן", name: "ריהוט גן", russianName: "Садовая мебель" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "354": {
    id: "354",
    name: "למטייל ולמתגייס",
    russianName: "Для туристов и призывников",
    subCategories: [
      { id: "תרמילים", name: "תרמילים", russianName: "Рюкзаки" },
      { id: "ציוד טיולים", name: "ציוד טיולים", russianName: "Туристическое снаряжение" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "355": {
    id: "355",
    name: "מוסיקה וסרטים",
    russianName: "Музыка и фильмы",
    subCategories: [
      { id: "תקליטים", name: "תקליטים", russianName: "Виниловые пластинки" },
      { id: "דיסקים", name: "דיסקים", russianName: "Диски" },
      { id: "סרטים", name: "סרטים", russianName: "Фильмы" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "357": {
    id: "357",
    name: "מנויים וכרטיסים",
    russianName: "Абонементы и билеты",
    subCategories: [
      { id: "כרטיסים", name: "כרטיסים", russianName: "Билеты" },
      { id: "מנויים", name: "מנויים", russianName: "Абонементы" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "359": {
    id: "359",
    name: "ספרות ומאמרים",
    russianName: "Книги и пресса",
    subCategories: [
      { id: "ספרים", name: "ספרים", russianName: "Книги" },
      { id: "מגזינים", name: "מגזינים", russianName: "Журналы" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "360": {
    id: "360",
    name: "עסקים למכירה/למסירה",
    russianName: "Готовый бизнес",
    subCategories: [
      { id: "עסקים למכירה", name: "עסקים למכירה", russianName: "Бизнес на продажу" },
      { id: "עסקים למסירה", name: "עסקים למסירה", russianName: "Бизнес в дар" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "361": {
    id: "361",
    name: "ציוד לתעשייה",
    russianName: "Промышленное оборудование",
    subCategories: [
      { id: "מכונות תעשייתיות", name: "מכונות תעשייתיות", russianName: "Промышленное оборудование" },
      { id: "ציוד ייצור", name: "ציוד ייצור", russianName: "Производственное оборудование" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "362": {
    id: "362",
    name: "ציוד סיעודי/רפואי",
    russianName: "Медтехника и уход",
    subCategories: [
      { id: "כיסאות גלגלים", name: "כיסאות גלגלים", russianName: "Инвалидные коляски" },
      { id: "מיטות חולים", name: "מיטות חולים", russianName: "Медицинские кровати" },
      { id: "ציוד סיעודי", name: "ציוד סיעודי", russianName: "Медтехника" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "363": {
    id: "363",
    name: "קוסמטיקה וטיפוח",
    russianName: "Косметика и уход",
    subCategories: [
      { id: "קוסמטיקה", name: "קוסמטיקה", russianName: "Косметика" },
      { id: "טיפוח", name: "טיפוח", russianName: "Уход" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "364": {
    id: "364",
    name: "קופונים/שוברי זיכוי/שונות",
    russianName: "Купоны, сертификаты, разное",
    subCategories: [
      { id: "קופונים", name: "קופונים", russianName: "Купоны" },
      { id: "שוברי זיכוי", name: "שוברי זיכוי", russianName: "Сертификаты" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "365": {
    id: "365",
    name: "תקשורת",
    russianName: "Связь и телеком",
    subCategories: [
      { id: "מודמים", name: "מודמים", russianName: "Модемы" },
      { id: "נתבים", name: "נתבים", russianName: "Роутеры" },
      { id: "אביזרי תקשורת", name: "אביזרי תקשורת", russianName: "Аксессуары связи" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "366": {
    id: "366",
    name: "אומנות",
    russianName: "Искусство",
    subCategories: [
      { id: "ציור", name: "ציור", russianName: "Живопись" },
      { id: "פיסול", name: "פיסול", russianName: "Скульптура" },
      { id: "אמנות דקורטיבית", name: "אמנות דקורטיבית", russianName: "Декоративное искусство" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "376": {
    id: "376",
    name: "מבנים ניידים",
    russianName: "Мобильные сооружения",
    subCategories: [
      { id: "קרוואנים", name: "קרוואנים", russianName: "Кемперы" },
      { id: "מודולים", name: "מודולים", russianName: "Модульные здания" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "377": {
    id: "377",
    name: "מוצרי Apple",
    russianName: "Продукция Apple",
    subCategories: [
      { id: "אייפון", name: "אייפון", russianName: "iPhone" },
      { id: "מק", name: "מק", russianName: "Mac" },
      { id: "אייפד", name: "אייפד", russianName: "iPad" },
      { id: "אביזרי Apple", name: "אביזרי Apple", russianName: "Аксессуары Apple" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "378": {
    id: "378",
    name: "סטריאו",
    russianName: "Стереосистемы",
    subCategories: [
      { id: "מערכות סטריאו", name: "מערכות סטריאו", russianName: "Стереосистемы" },
      { id: "רמקולים", name: "רמקולים", russianName: "Колонки" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "379": {
    id: "379",
    name: "ספרות וחומרי לימוד",
    russianName: "Книги и учебные материалы",
    subCategories: [
      { id: "ספרי לימוד", name: "ספרי לימוד", russianName: "Учебники" },
      { id: "חומרי לימוד", name: "חומרי לימוד", russianName: "Учебные материалы" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "380": {
    id: "380",
    name: "ציוד לאירועים",
    russianName: "Оборудование для мероприятий",
    subCategories: [
      { id: "שולחנות אירועים", name: "שולחנות אירועים", russianName: "Столы для мероприятий" },
      { id: "כיסאות אירועים", name: "כיסאות אירועים", russianName: "Стулья для мероприятий" },
      { id: "תאורה לאירועים", name: "תאורה לאירועים", russianName: "Освещение для мероприятий" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "381": {
    id: "381",
    name: "ציוד לבית ספר",
    russianName: "Школьные принадлежности",
    subCategories: [
      { id: "תיקים", name: "תיקים", russianName: "Рюкзаки" },
      { id: "כלי כתיבה", name: "כלי כתיבה", russianName: "Канцтовары" },
      { id: "אביזרי לימוד", name: "אביזרי לימוד", russianName: "Школьные принадлежности" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "221": {
    id: "221",
    name: "ציוד לעסקים",
    russianName: "Оборудование для бизнеса",
    subCategories: [
      { id: "ריהוט משרדי", name: "ריהוט משרדי", russianName: "Офисная мебель" },
      { id: "מחשבים וציוד", name: "מחשבים וציוד", russianName: "Компьютеры и оборудование" },
      { id: "מכונות", name: "מכונות", russianName: "Станки" },
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  },
  "222":{
    id: "222",
    name: "אחר",
    russianName: "Другое",
    subCategories: [
      { id: "אחר", name: "אחר", russianName: "Другое" },
    ],
  }
};
