import {
  SpecialVehicleCategory,
  SpecialVehicleCategoryId,
} from "./types/specialVehicleCategory.schema";

export const specialVehicleCategoriesMap = {
  A1B2C3: {
    id: "A1B2C3",
    name: "אוטובוסים",
    russianName: "Автобусы",
    models: [
      { id: "M0A1B2", name: "אביזרים", russianName: "Аксессуары" },
      { id: "M0A1B3", name: "איווקו", russianName: "Ивеко / Iveco" },
      { id: "M0A1B4", name: "דאף", russianName: "ДАФ / DAF" },
      { id: "M0A1B5", name: "וולוו", russianName: "Вольво / Volvo" },
      { id: "M0A1B6", name: "טמסה", russianName: "Тамса / TAMSA" },
      { id: "M0A1B7", name: "יוטונג", russianName: "Ютонг / Yutong" },
      { id: "M0A1B8", name: "כללי", russianName: "Общее" },
      { id: "M0A1B9", name: "מאן", russianName: "МАН / MAN" },
      {
        id: "M0A1C0",
        name: "מרצדס",
        russianName: "Мерседес-Бенц / Mercedes-Benz",
      },
      { id: "M0A1C1", name: "סקניה", russianName: "Скания / Scania" },
      { id: "M0A1C2", name: "קינג לונג", russianName: "Кинг Лонг / King Long" },
    ],
  },

  D4E5F6: {
    id: "D4E5F6",
    name: "אוטוקראוון",
    russianName: "Автодома / Motorhome",
    models: [
      { id: "M0B2A1", name: "אביזרים", russianName: "Аксессуары" },
      { id: "M0B2A2", name: "אוטוקראוון", russianName: "Автодом / Motorhome" },
      { id: "M0B2A3", name: "אחר", russianName: "Другое" },
    ],
  },

  G7H8J9: {
    id: "G7H8J9",
    name: "אופנועי ים",
    russianName: "Гидроциклы / Jet Ski",
    models: [
      { id: "M0C3A1", name: "אחר", russianName: "Другое" },
      {
        id: "M0C3A2",
        name: "טייגר שארק",
        russianName: "Тайгер Шарк / Tiger Shark",
      },
      { id: "M0C3A3", name: "ימאהה", russianName: "Ямаха / Yamaha" },
      { id: "M0C3A4", name: "סידו", russianName: "Си-Ду / Sea-Doo" },
      { id: "M0C3A5", name: "קוואסאקי", russianName: "Кавасаки / Kawasaki" },
    ],
  },

  K1L2M3: {
    id: "K1L2M3",
    name: "אחרים",
    russianName: "Другое",
    models: [
      { id: "M0D4A1", name: "באגי", russianName: "Багги / Buggy" },
      { id: "M0D4A2", name: "כללי", russianName: "Общее" },
    ],
  },

  N4P5Q6: {
    id: "N4P5Q6",
    name: "גרורים ונתמכים",
    russianName: "Прицепы и полуприцепы",
    models: [
      { id: "M0E5A1", name: "אביזרים", russianName: "Аксессуары" },
      { id: "M0E5A2", name: "כללי", russianName: "Общее" },
    ],
  },

  R7S8T9: {
    id: "R7S8T9",
    name: "זכות ציבורית למונית",
    russianName: "Лицензия на такси",
    models: [
      { id: "M0F6A1", name: "השכרת זכות", russianName: "Аренда лицензии" },
      { id: "M0F6A2", name: "כללי", russianName: "Общее" },
      { id: "M0F6A3", name: "מחפש", russianName: "Ищу" },
      { id: "M0F6A4", name: "מכירת זכות", russianName: "Продажа лицензии" },
    ],
  },

  U1V2W3: {
    id: "U1V2W3",
    name: "טרקטור",
    russianName: "Тракторы",
    models: [{ id: "M0G7A1", name: "כללי", russianName: "Общее" }],
  },

  X4Y5Z6: {
    id: "X4Y5Z6",
    name: "טרקטורונים",
    russianName: "Квадроциклы / ATV",
    models: [
      { id: "M0H8A1", name: "ACCESS", russianName: "Аксес / ACCESS" },
      { id: "M0H8A2", name: "CFMOTO", russianName: "СиЭфМото / CFMOTO" },
      {
        id: "M0H8A3",
        name: "John Deere",
        russianName: "Джон Дир / John Deere",
      },
      { id: "M0H8A4", name: "Textron", russianName: "Текстрон / Textron" },
      { id: "M0H8A5", name: "TGB", russianName: "ТиДжиБи / TGB" },
      { id: "M0H8A6", name: "אביזרים", russianName: "Аксессуары" },
      { id: "M0H8A7", name: "אדלי", russianName: "Адли / Adly" },
      { id: "M0H8A8", name: "אחר", russianName: "Другое" },
      { id: "M0H8A9", name: "ארו", russianName: "Аро / Aro" },
      { id: "M0H8B0", name: "ארקטיק", russianName: "Арктик Кэт / Arctic Cat" },
      { id: "M0H8B1", name: "באגי", russianName: "Багги / Buggy" },
      { id: "M0H8B2", name: "באקאי (מעופף)", russianName: "Бакай (летающий)" },
      {
        id: "M0H8B3",
        name: "בומברדיר/ קאן אם",
        russianName: "Кан-Ам / Can-Am",
      },
      { id: "M0H8B4", name: "דינלי", russianName: "Динли / Dinli" },
      { id: "M0H8B5", name: "הונדה", russianName: "Хонда / Honda" },
      { id: "M0H8B6", name: "הייסן", russianName: "Хайсен / Haisen" },
      {
        id: "M0H8B7",
        name: "טרקטורון דשא",
        russianName: "Газонный квадроцикл",
      },
      { id: "M0H8B8", name: "טרקסטאר", russianName: "Трекстар / Trackstar" },
      { id: "M0H8B9", name: "יוסאנג", russianName: "Хёсунг / Hyosung" },
      { id: "M0H8C0", name: "ימאהה", russianName: "Ямаха / Yamaha" },
      { id: "M0H8C1", name: "מיול", russianName: "Мьюл / Mule" },
      { id: "M0H8C2", name: "נשיונל מוטוקרוס", russianName: "Нэшнл Мотокросс" },
      { id: "M0H8C3", name: "סאגווי", russianName: "Сегвей / Segway" },
      { id: "M0H8C4", name: "סאן יאנג", russianName: "Сан Янг / SYM" },
      { id: "M0H8C5", name: "סוזוקי", russianName: "Сузуки / Suzuki" },
      { id: "M0H8C6", name: "פולריס", russianName: "Поларис / Polaris" },
      { id: "M0H8C7", name: "קוואסקי", russianName: "Кавасаки / Kawasaki" },
      { id: "M0H8C8", name: "קי טי אם", russianName: "КТМ / KTM" },
      { id: "M0H8C9", name: "קימקו", russianName: "Кимко / Kymco" },
      { id: "M0H8D0", name: "שירומיקה", russianName: "Широмика" },
      { id: "M0H8D1", name: "תומקר", russianName: "Томкар / Tomcar" },
    ],
  },

  A7C8D9: {
    id: "A7C8D9",
    name: 'מבי"ס לנהיגה',
    russianName: "Автошколы",
    models: [{ id: "M0I9A1", name: "כללי", russianName: "Общее" }],
  },

  E1F2G3: {
    id: "E1F2G3",
    name: "מוניות",
    russianName: "Такси",
    models: [{ id: "M0J0A1", name: "כללי", russianName: "Общее" }],
  },
  B2C3D4: {
    id: "B2C3D4",
    name: "מחרשה",
    russianName: "Плуги",
    models: [{ id: "M2A1B1", name: "כללי", russianName: "Общее" }],
  },

  E5F6G7: {
    id: "E5F6G7",
    name: "מיניבוסים",
    russianName: "Микроавтобусы",
    models: [
      { id: "M2B1A1", name: "אביזרים", russianName: "Аксессуары" },
      { id: "M2B1A2", name: "איווקו", russianName: "Ивеко / Iveco" },
      { id: "M2B1A3", name: "דאף", russianName: "ДАФ / DAF" },
      { id: "M2B1A4", name: "וולוו", russianName: "Вольво / Volvo" },
      { id: "M2B1A5", name: "כללי", russianName: "Общее" },
      { id: "M2B1A6", name: "מאן", russianName: "МАН / MAN" },
      {
        id: "M2B1A7",
        name: "מרצדס",
        russianName: "Мерседес-Бенц / Mercedes-Benz",
      },
      {
        id: "M2B1A8",
        name: "פולקסווגן",
        russianName: "Фольксваген / Volkswagen",
      },
      { id: "M2B1A9", name: "פורד", russianName: "Форд / Ford" },
      { id: "M2B1B0", name: "פיאט", russianName: "Фиат / Fiat" },
      { id: "M2B1B1", name: "רנו", russianName: "Рено / Renault" },
      { id: "M2B1B2", name: "שברולט", russianName: "Шевроле / Chevrolet" },
    ],
  },

  H8J9K1: {
    id: "H8J9K1",
    name: "מלגזה",
    russianName: "Погрузчики",
    models: [{ id: "M2C1A1", name: "כללי", russianName: "Общее" }],
  },

  L2M3N4: {
    id: "L2M3N4",
    name: "משאיות",
    russianName: "Грузовики",
    models: [
      { id: "M2D1A1", name: "GMC", russianName: "Джи-Эм-Си / GMC" },
      { id: "M2D1A2", name: "אביזרים", russianName: "Аксессуары" },
      { id: "M2D1A3", name: "אחר", russianName: "Другое" },
      { id: "M2D1A4", name: "איווקו", russianName: "Ивеко / Iveco" },
      {
        id: "M2D1A5",
        name: "אינטרנשיונל",
        russianName: "Интернэшнл / International",
      },
      { id: "M2D1A6", name: "איסוזו", russianName: "Исузу / Isuzu" },
      { id: "M2D1A7", name: "דאף", russianName: "ДАФ / DAF" },
      { id: "M2D1A8", name: "וולוו", russianName: "Вольво / Volvo" },
      { id: "M2D1A9", name: "טויוטה", russianName: "Тойота / Toyota" },
      { id: "M2D1B0", name: "מאן", russianName: "МАН / MAN" },
      { id: "M2D1B1", name: "מיצובישי", russianName: "Мицубиси / Mitsubishi" },
      { id: "M2D1B2", name: "מק", russianName: "МАК / Mack" },
      {
        id: "M2D1B3",
        name: "מרצדס",
        russianName: "Мерседес-Бенц / Mercedes-Benz",
      },
      { id: "M2D1B4", name: "ניסן", russianName: "Ниссан / Nissan" },
      { id: "M2D1B5", name: "סקניה", russianName: "Скания / Scania" },
      {
        id: "M2D1B6",
        name: "פולקסווגן",
        russianName: "Фольксваген / Volkswagen",
      },
      { id: "M2D1B7", name: "פורד", russianName: "Форд / Ford" },
      { id: "M2D1B8", name: "קנוורת'", russianName: "Кенворт / Kenworth" },
      { id: "M2D1B9", name: "רנו", russianName: "Рено / Renault" },
      { id: "M2D1C0", name: "שברולט", russianName: "Шевроле / Chevrolet" },
    ],
  },

  P5Q6R7: {
    id: "P5Q6R7",
    name: "קלנועיות",
    russianName: "Электроскутеры для инвалидов",
    models: [
      { id: "M2E1A1", name: "BREEZE", russianName: "Бриз / Breeze" },
      { id: "M2E1A2", name: "KIMCO", russianName: "Кимко / Kymco" },
      { id: "M2E1A3", name: "MERITZ", russianName: "Мериц / Merits" },
      { id: "M2E1A4", name: "PRIDE", russianName: "Прайд / Pride" },
      {
        id: "M2E1A5",
        name: "SHOP RIDER",
        russianName: "Шоп Райдер / Shoprider",
      },
      { id: "M2E1A6", name: "אביזרים", russianName: "Аксессуары" },
      { id: "M2E1A7", name: "אחר", russianName: "Другое" },
    ],
  },

  S8T9U1: {
    id: "S8T9U1",
    name: "קראוון נגרר",
    russianName: "Прицепы-дачи / Caravan",
    models: [
      {
        id: "M2F1A1",
        name: "Black Series",
        russianName: "Блэк Сириес / Black Series",
      },
      { id: "M2F1A2", name: "Knaus", russianName: "Кнаус / Knaus" },
      {
        id: "M2F1A3",
        name: "STERCKEMAN",
        russianName: "Стеркман / Sterckeman",
      },
      { id: "M2F1A4", name: "T@b", russianName: "Тэб / T@b" },
      { id: "M2F1A5", name: "Tabbert", russianName: "Табберт / Tabbert" },
      { id: "M2F1A6", name: "Weinsberg", russianName: "Вайнсберг / Weinsberg" },
      { id: "M2F1A7", name: "אדריה", russianName: "Адрия / Adria" },
      { id: "M2F1A8", name: "אחר", russianName: "Другое" },
      { id: "M2F1A9", name: "הובי", russianName: "Хобби / Hobby" },
      { id: "M2F1B0", name: "נחלים", russianName: "Нахалим" },
    ],
  },

  V2W3X4: {
    id: "V2W3X4",
    name: "רכב אספנות",
    russianName: "Коллекционные автомобили",
    models: [
      { id: "M2G1A1", name: " כללי", russianName: "Общее" },
      { id: "M2G1A2", name: "MG", russianName: "Эм-Джи / MG" },
      { id: "M2G1A3", name: "אביזרים", russianName: "Аксессуары" },
      {
        id: "M2G1A4",
        name: "אולדסמוביל",
        russianName: "Олдсмобиль / Oldsmobile",
      },
      { id: "M2G1A5", name: "אוסטין", russianName: "Остин / Austin" },
      { id: "M2G1A6", name: "אופל", russianName: "Опель / Opel" },
      { id: "M2G1A7", name: "אופנועים", russianName: "Мотоциклы" },
      {
        id: "M2G1A8",
        name: "אלפא רומאו",
        russianName: "Альфа Ромео / Alfa Romeo",
      },
      { id: "M2G1A9", name: "ב.מ.וו", russianName: "БМВ / BMW" },
      { id: "M2G1B0", name: "ביואיק", russianName: "Бьюик / Buick" },
      { id: "M2G1B1", name: "ג'יפ CJ", russianName: "Джип CJ / Jeep CJ" },
      { id: "M2G1B2", name: "'דודג", russianName: "Додж / Dodge" },
      { id: "M2G1B3", name: "הילמן", russianName: "Хиллман / Hillman" },
      { id: "M2G1B4", name: "וויליס", russianName: "Виллис / Willys" },
      { id: "M2G1B5", name: "וולוו", russianName: "Вольво / Volvo" },
      { id: "M2G1B6", name: "טריומף", russianName: "Триумф / Triumph" },
      { id: "M2G1B7", name: "יגואר", russianName: "Ягуар / Jaguar" },
      { id: "M2G1B8", name: "לינקולן", russianName: "Линкольн / Lincoln" },
      { id: "M2G1B9", name: "לנדרובר", russianName: "Ленд Ровер / Land Rover" },
      { id: "M2G1C0", name: "לנציה", russianName: "Лянча / Lancia" },
      { id: "M2G1C1", name: "מוריס", russianName: "Моррис / Morris" },
      {
        id: "M2G1C2",
        name: "מיני מיינור",
        russianName: "Мини Майнер / Mini Minor",
      },
      {
        id: "M2G1C3",
        name: "מרצדס",
        russianName: "Мерседес-Бенц / Mercedes-Benz",
      },
      { id: "M2G1C4", name: "סאאב", russianName: "Сааб / Saab" },
      { id: "M2G1C5", name: "סובארו", russianName: "Субару / Subaru" },
      { id: "M2G1C6", name: "סוסיתא", russianName: "Сусита" },
      { id: "M2G1C7", name: "סיטרואן", russianName: "Ситроен / Citroën" },
      {
        id: "M2G1C8",
        name: "פולקסוואגן",
        russianName: "Фольксваген / Volkswagen",
      },
      { id: "M2G1C9", name: "פונטיאק", russianName: "Понтиак / Pontiac" },
      { id: "M2G1D0", name: "פורד", russianName: "Форд / Ford" },
      { id: "M2G1D1", name: "פורשה", russianName: "Порше / Porsche" },
      { id: "M2G1D2", name: "פיאט", russianName: "Фиат / Fiat" },
      { id: "M2G1D3", name: "פיג'ו", russianName: "Пежо / Peugeot" },
      { id: "M2G1D4", name: "פליימות", russianName: "Плимут / Plymouth" },
      { id: "M2G1D5", name: "קאדילק", russianName: "Кадиллак / Cadillac" },
      {
        id: "M2G1D6",
        name: "רולס רויס",
        russianName: "Роллс-Ройс / Rolls-Royce",
      },
      { id: "M2G1D7", name: "רנו", russianName: "Рено / Renault" },
      { id: "M2G1D8", name: "שברולט", russianName: "Шевроле / Chevrolet" },
    ],
  },

  Y5Z6A7: {
    id: "Y5Z6A7",
    name: 'רכב צמ"ה',
    russianName: "Строительная техника",
    models: [
      { id: "M2H1A1", name: "דחפורים", russianName: "Бульдозеры" },
      { id: "M2H1A2", name: "כדור הריסה", russianName: "Шар-разрушитель" },
      { id: "M2H1A3", name: "מגרדת", russianName: "Грейдер" },
      { id: "M2H1A4", name: "מחפר", russianName: "Экскаватор" },
      { id: "M2H1A5", name: "מחפרון", russianName: "Экскаватор-погрузчик" },
      { id: "M2H1A6", name: "מיני מחפר", russianName: "Мини-экскаватор" },
      { id: "M2H1A7", name: "מיני מעמיס", russianName: "Мини-погрузчик" },
      { id: "M2H1A8", name: "מכבש", russianName: "Каток" },
      { id: "M2H1A9", name: "מכונת קידוח", russianName: "Буровая установка" },
      { id: "M2H1B0", name: "מלגזה", russianName: "Погрузчик" },
      { id: "M2H1B1", name: "מנוף", russianName: "Кран" },
      {
        id: "M2H1B2",
        name: "מעמיס טלסקופי",
        russianName: "Телескопический погрузчик",
      },
      { id: "M2H1B3", name: "מערבל בטון", russianName: "Бетономешалка" },
      { id: "M2H1B4", name: "מפלסת", russianName: "Планировщик" },
      { id: "M2H1B5", name: "מקרצפת כביש", russianName: "Дорожная фреза" },
      { id: "M2H1B6", name: "משאבת בטון", russianName: "Бетононасос" },
      { id: "M2H1B7", name: "עגורן", russianName: "Подъёмный кран" },
      { id: "M2H1B8", name: "שופל", russianName: "Фронтальный погрузчик" },
    ],
  },

  B8C9D1: {
    id: "B8C9D1",
    name: "רכבים תפעוליים",
    russianName: "Служебные электромобили",
    models: [
      { id: "M2J1A1", name: "CLUB CAR", russianName: "Клаб Кар / Club Car" },
      { id: "M2J1A2", name: "EASY GO", russianName: "Изи Го / EZ-GO" },
      { id: "M2J1A3", name: "E-CAR", russianName: "И-Кар / E-Car" },
      { id: "M2J1A4", name: "HDK", russianName: "Эйч-Ди-Кей / HDK" },
      { id: "M2J1A5", name: "ITALCAR", russianName: "Италкар / Italcar" },
      { id: "M2J1A6", name: "Marshell", russianName: "Маршелл / Marshell" },
      { id: "M2J1A7", name: "MELEX", russianName: "Мелекс / Melex" },
      { id: "M2J1A8", name: "PARK CAR", russianName: "Парк Кар / Park Car" },
      { id: "M2J1A9", name: "Sun Car", russianName: "Сан Кар / Sun Car" },
      {
        id: "M2J1B0",
        name: "TAYLOR DUNNE",
        russianName: "Тейлор Данн / Taylor-Dunn",
      },
      { id: "M2J1B1", name: "VCAR", russianName: "ВиКар / VCar" },
      { id: "M2J1B2", name: "YAMAHA", russianName: "Ямаха / Yamaha" },
      { id: "M2J1B3", name: "ZYCAR", russianName: "ЗиКар / Zycar" },
      { id: "M2J1B4", name: "אביזרים", russianName: "Аксессуары" },
      { id: "M2J1B5", name: "כללי", russianName: "Общее" },
    ],
  },
} satisfies Record<SpecialVehicleCategoryId, SpecialVehicleCategory>;
