name: deploy-professionals 

on:
  push:
    branches:
      - master
    paths:
      - 'professionals/**' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd professionals && docker build -t rosengray/sima-professionals .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push rosengray/sima-professionals
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save sima
      - run: kubectl rollout restart deployment professionals-depl
