name: tests-professionals

on:
  pull_request:
    paths:
      - 'professionals/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd professionals && npm install && npm run test:ci
    
